#ifndef DESKTOP_H
#define DESKTOP_H

#include <stdint.h>
#include "ui_vga.h"

// Theme colors
#define THEME_TASKBAR_BG VGA_DARK_GRAY
#define THEME_TASKBAR_FG VGA_WHITE
#define THEME_LOGO_FG VGA_LIGHT_CYAN
#define THEME_CLOCK_FG VGA_LIGHT_GRAY
#define THEME_DOCK_BG VGA_BLACK
#define THEME_DOCK_FG VGA_LIGHT_GRAY
#define THEME_DOCK_SEL_FG VGA_LIGHT_CYAN
#define THEME_DOCK_SEL_BG VGA_DARK_GRAY
#define THEME_WS_BG VGA_BLACK
#define THEME_STATUS_BG VGA_DARK_GRAY
#define THEME_STATUS_FG VGA_LIGHT_GRAY
#define THEME_STATUS_OK VGA_LIGHT_GREEN
#define THEME_WIN_BORDER VGA_CYAN
#define THEME_WIN_TITLE_BG VGA_BLUE
#define THEME_WIN_TITLE_FG VGA_WHITE
#define THEME_WIN_BG VGA_BLACK
#define THEME_WIN_FG VGA_LIGHT_GRAY
#define THEME_PROMPT_FG VGA_LIGHT_CYAN
#define THEME_CMD_FG VGA_WHITE
#define THEME_OK_FG VGA_LIGHT_GREEN
#define THEME_ERR_FG VGA_LIGHT_RED
#define THEME_DIM_FG VGA_DARK_GRAY

// Layout regions
#define REGION_TASKBAR_ROW 0
#define REGION_TASKBAR_COL 0
#define REGION_TASKBAR_H 1
#define REGION_TASKBAR_W VGA_COLS

#define REGION_DOCK_ROW 1
#define REGION_DOCK_COL 0
#define REGION_DOCK_H (VGA_ROWS - 2)
#define REGION_DOCK_W 10

#define REGION_SEPARATOR_ROW 1
#define REGION_SEPARATOR_COL 10
#define REGION_SEPARATOR_H (VGA_ROWS - 2)
#define REGION_SEPARATOR_W 1

#define REGION_WORKSPACE_ROW 1
#define REGION_WORKSPACE_COL 11
#define REGION_WORKSPACE_H (VGA_ROWS - 2)
#define REGION_WORKSPACE_W (VGA_COLS - 11)

#define REGION_STATUSBAR_ROW (VGA_ROWS - 1)
#define REGION_STATUSBAR_COL 0
#define REGION_STATUSBAR_H 1
#define REGION_STATUSBAR_W VGA_COLS

void desktop_init(void);
void taskbar_update_clock(void);
void statusbar_update_ticks(uint32_t ticks);

#endif